### ISSUE TITLE
Status N/A on PiHole Dashboard

### ISSUE THREAD

**Issue by CopiousWaistcoats** [Brandawg93/Pi-Hole-Monitoring#41]
I have an issue where the status panel on the PiHole dash reports N/A. I have gone through the pre-existing issues, and tried the following already:

-verified I can access pi.hole
-verified piHole API is enabled
-changed pi.hole to the IP address of the pihole  (this fixed the other panels in the top row, which had previously be reding 'No Data')

Any ideas?

![image](https://user-images.githubusercontent.com/48248415/189485874-d1b5ca15-68eb-49df-9e52-9e9654934293.png)

**Comment by keanugithub** [comment]
Am having the same issue, please help. Thank you in advance!

**Comment by keanugithub** [comment]
Am having the same issue, please help. Thank you in advance! It seems that when I change to fields option to status, it shows enabled. However, I can't seem to save it, I can only apply. Is it really like this? Sorry, I don't really understand this fully yet.
![image](https://user-images.githubusercontent.com/98110531/190213981-3af82749-dfe6-4bec-9b9c-43fea4638904.png)
![image](https://user-images.githubusercontent.com/98110531/190214236-2aba781e-089d-4f65-900f-b8ccf122e03f.png)

when I changed the fields option to enable:
![image](https://user-images.githubusercontent.com/98110531/190214433-e6295c33-17ac-499b-a934-b2a90950e145.png)

I can't save, is this like this or is there a setting I should do?
![image](https://user-images.githubusercontent.com/98110531/190214534-c714652f-64aa-4e14-bd4e-b7f366c6e89d.png)

Btw, I can't manually try to save or copy to json file since I'm only ssh-ing on my pi and its only a light install only CLI...

**Comment by CopiousWaistcoats** [comment]
You fixed my issue - and I think I might be able to help with yours!

I assume you are viewing the dashboard in a browser on a separate device from the CLI-only pi. 

If you copy the JSON to clipboard (or save the file - it should download in-browser) then mouse over the Dashboards menu and select import - this should allow you to paste or upload the JSON, and add this as alocal copy of the dashboard that you can modify and save. Not sure if this is the "right" way to do this, but it worked for me!

**Comment by keanugithub** [comment]
You know what, yes I am viewing the dashboard in a separate device' browser, and that is one way to do it. But what I did to be able to edit and save the dashboard with no error was to add this line  ` allowUiUpdates: false` and set it to `true` in my dashboard.yml. Again as you've said and I agree, I don't know if this is the right way to do this, but for now, I guess this will do as a workaround if anyone also comes across this problem. Just follow what I did, first, edit the database.yml then you can now edit and save the dashboard. Change the fields of status to status from its original selection, numerical fields. Hope I helped.

![image](https://user-images.githubusercontent.com/98110531/190323028-3c79abb1-c974-4864-b825-acea0e6f7c7a.png)
![image](https://user-images.githubusercontent.com/98110531/190322477-247ccedf-6f36-4a4b-b36a-06e656086c7c.png)
